/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.77
 * Generated at: 2023-05-18 08:04:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;
import bbs.Bbs;
import bbs.BbsDAO;
import reply.Reply;
import reply.ReplyDAO;
import java.util.ArrayList;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("bbs.Bbs");
    _jspx_imports_classes.add("reply.Reply");
    _jspx_imports_classes.add("bbs.BbsDAO");
    _jspx_imports_classes.add("reply.ReplyDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\" , initial-scale=\"1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>JSP 게시판 웹 게시판</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

	String userID = null;
	if (session.getAttribute("userID") != null) {
		userID = (String) session.getAttribute("userID");
	}
	int bbsID = 0;
	if (request.getParameter("bbsID") != null) {
		bbsID = Integer.parseInt(request.getParameter("bbsID"));
	}
	if (bbsID == 0) {
		PrintWriter script = response.getWriter();
		script.println("<script>");
		script.println("alert('유효하지 않은 글입니다.')");
		script.println("location.href = 'bbs.jsp'");
		script.println("</script>");
	}
	Bbs bbs = new BbsDAO().getBbs(bbsID);
	
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		//수정 버튼을 클릭시 클릭한 댓글에 수정을 위한 태그추가\r\n");
      out.write("		var updateID=0;\r\n");
      out.write("		function update(replyID, bbsID){\r\n");
      out.write("			if (document.getElementById('reComment') != null) {\r\n");
      out.write("				cancel(\"reComment\");\r\n");
      out.write("			}\r\n");
      out.write("			if (document.getElementById('reCommentUpdate') != null) {\r\n");
      out.write("				cancel(\"reCommentUpdate\");\r\n");
      out.write("				var reContent = document.getElementById('content' + this.updateID);\r\n");
      out.write("				reContent.setAttribute(\"style\", \"\");\r\n");
      out.write("			}\r\n");
      out.write("			this.updateID = replyID;\r\n");
      out.write("			var Content = document.getElementById('update' + replyID).innerText;\r\n");
      out.write("			var reComment = document.getElementById('update' + replyID);\r\n");
      out.write("			var replyContent = document.getElementById('content' + replyID);\r\n");
      out.write("			replyContent.setAttribute(\"style\", \"display:none\");\r\n");
      out.write("			var reCommentUpdate = document.createElement(\"form\")\r\n");
      out.write("			reCommentUpdate.setAttribute(\"id\", \"reCommentUpdate\");\r\n");
      out.write("			reCommentUpdate.setAttribute(\"method\", \"post\");\r\n");
      out.write("			reCommentUpdate.setAttribute(\"action\", \"replyUpdateAction.jsp?bbsID=\"+ bbsID);\r\n");
      out.write("			\r\n");
      out.write("			reCommentUpdate.innerHTML = \"<textarea  class='form-control' placeholder='답글 내용'\"\r\n");
      out.write("					+ \"name='replyContent' maxlength='1000' style='height: 70px; resize: none;'>\" + Content + \"</textarea>\"\r\n");
      out.write("					+ \"<input type='hidden' name='replyID' value='\" + replyID + \"'>\" \r\n");
      out.write("					+ \"<input type='submit' class='btn btn-primary pull-right' value='답글 수정'>\"\r\n");
      out.write("					+ \"<a class='btn btn-primary pull-right' href='javascript:void(0);'\" \r\n");
      out.write("					+ \"name='reCommentUpdate' onclick='updateCancel(this.name, \"+ replyID +\");' >취소</a>\";\r\n");
      out.write("			\r\n");
      out.write("			reComment.appendChild(reCommentUpdate);\r\n");
      out.write("		}\r\n");
      out.write("		function cancel(areaID) {\r\n");
      out.write("			var reComment = document.getElementById(areaID);\r\n");
      out.write("			var parent = reComment.parentElement;\r\n");
      out.write("			parent.removeChild(reComment);\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		function updateCancel(areaID,replyID) {\r\n");
      out.write("			var reComment = document.getElementById(areaID);\r\n");
      out.write("			var parent = reComment.parentElement;\r\n");
      out.write("			parent.removeChild(reComment);\r\n");
      out.write("			var reContent = document.getElementById('content' + replyID);\r\n");
      out.write("			reContent.setAttribute(\"style\", \"\");\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		function reComment(replyID, groupID, bbsID, groupUserID) {\r\n");
      out.write("			if (document.getElementById('reComment') != null) {\r\n");
      out.write("				cancel(\"reComment\");\r\n");
      out.write("			}\r\n");
      out.write("			if (document.getElementById('reCommentUpdate') != null) {\r\n");
      out.write("				cancel(\"reCommentUpdate\");\r\n");
      out.write("			}\r\n");
      out.write("				var newReplyTr = document.createElement(\"tr\")\r\n");
      out.write("				newReplyTr.setAttribute(\"id\", \"reComment\");\r\n");
      out.write("				newReplyTr.setAttribute(\"name\", 'reply' + replyID);\r\n");
      out.write("				newReplyTr.innerHTML = \"<td></td>\";\r\n");
      out.write("				\r\n");
      out.write("				var newReplyTd = document.createElement(\"td\")\r\n");
      out.write("				\r\n");
      out.write("				var reCommentForm = document.createElement(\"form\")\r\n");
      out.write("				reCommentForm.setAttribute(\"method\", \"post\");\r\n");
      out.write("				reCommentForm.setAttribute(\"action\", \"replyAction.jsp\");\r\n");
      out.write("				\r\n");
      out.write("				reCommentForm.innerHTML = \"<textarea class='form-control' placeholder='답글 내용'\"\r\n");
      out.write("						+ \"name='replyContent' maxlength='1000' style='height: 70px; resize: none;'></textarea>\"\r\n");
      out.write("						+ \"<input type='hidden' name='groupID' value='\" + groupID + \"'>\" \r\n");
      out.write("						+ \"<input type='hidden' name='groupUserID' value='\" + groupUserID + \"'>\" \r\n");
      out.write("						+ \"<input type='hidden' name='bbsID' value='\" + bbsID + \"'>\" \r\n");
      out.write("						+ \"<input type='submit' class='btn btn-primary pull-right' value='답글 작성'>\"\r\n");
      out.write("						+ \"<a class='btn btn-primary pull-right' href='javascript:void(0);' name='reComment' onclick='cancel(this.name);' >취소</a>\";\r\n");
      out.write("				newReplyTd.appendChild(reCommentForm);\r\n");
      out.write("				newReplyTr.appendChild(newReplyTd);\r\n");
      out.write("						\r\n");
      out.write("				var reCommentLocation = document.getElementById('reply' + replyID);\r\n");
      out.write("				reCommentLocation.appendChild(newReplyTr);\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	<nav class=\"navbar navbar-default\">\r\n");
      out.write("		<div class=\"navbar-header\">\r\n");
      out.write("			<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("				data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("				aria-expanded=\"false\">\r\n");
      out.write("				<span class=\"icon-bar\"></span>\r\n");
      out.write("				<!-- 메뉴 오른쪽 아이콘 바 -->\r\n");
      out.write("				<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"main.jsp\">JSP 교육용 게시판</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"collapse navbar-collapse\"\r\n");
      out.write("			id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("			<ul class=\"nav navbar-nav\">\r\n");
      out.write("				<!-- active 현제 접속한곳을 알려줌 -->\r\n");
      out.write("				<li><a href=\"main.jsp\">메인</a></li>\r\n");
      out.write("				<li class=\"active\"><a href=\"bbs.jsp\">게시판</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			");

			if (userID == null) {
			
      out.write("\r\n");
      out.write("			<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("				<li class=\"dropdown\">\r\n");
      out.write("					<!-- #은 가리키는 링크가 없다는 의미 --> <a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("					data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("					aria-expanded=\"false\">접속하기<span class=\"caret\"></span></a>\r\n");
      out.write("					<ul class=\"dropdown-menu\">\r\n");
      out.write("						<li><a href=\"login.jsp\">로그인</a></li>\r\n");
      out.write("						<li><a href=\"join.jsp\">회원가입</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("			");

			} else {
			
      out.write("\r\n");
      out.write("			<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("				<li class=\"dropdown\">\r\n");
      out.write("					<a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("					data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("					aria-expanded=\"false\">회원관리<span class=\"caret\"></span></a>\r\n");
      out.write("					<ul class=\"dropdown-menu\">\r\n");
      out.write("						<li><a href=\"logoutAction.jsp\">로그아웃</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<table class=\"table table-striped\"\r\n");
      out.write("				style=\"text-align: center; border: 1px solid #dddddd\">\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- colspan 열을 몇 줄만큼 차지 할지 -->\r\n");
      out.write("						<th colspan=\"3\"\r\n");
      out.write("							style=\"background-color: #eeeeee; text-align: center;\">게시판</th>\r\n");
      out.write("\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"3\" style=\"text-align: center;\">");
      out.print(bbs.getBbsTitle()
							.replaceAll("<", "&lt")
							.replaceAll(">", "&gt")
							.replaceAll("\n", "<br>"));
      out.write("\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- 작성자 -->\r\n");
      out.write("						<td colspan=\"2\">");
      out.print(bbs.getUserID());
      out.write("</td>\r\n");
      out.write("						<!-- 작성일 -->\r\n");
      out.write("						<td colspan=\"2\">");
      out.print(bbs.getBbsDate()
							.substring(0, 11) + bbs.getBbsDate().substring(11, 13) + "시"
							+ bbs.getBbsDate().substring(14, 16) + "분");
      out.write("\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"3\" style=\"min-height: 200px; text-align: left;\">\r\n");
      out.write("							");
      out.print(bbs.getBbsContent()
								.replaceAll(" ", "&nbsp;")
								.replaceAll("<", "&lt")
								.replaceAll(">", "&gt")
								.replaceAll("\n",
								"<br>"));
      out.write("\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("			<table class=\"table table-striped\"\r\n");
      out.write("				style=\"text-align: center; border: 1px solid #dddddd\">\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- colspan 열을 몇 줄만큼 차지 할지 -->\r\n");
      out.write("						<th colspan=\"2\"\r\n");
      out.write("							style=\"background-color: #eeeeee; text-align: center;\">댓글 목록</th>\r\n");
      out.write("\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				");

				ReplyDAO replyDAO = new ReplyDAO();
				ArrayList<Reply> replyList = replyDAO.getList(bbsID, 0);
				int replyID;
				for (int i = 0; i < replyList.size(); i++) {
					String replyUserID = replyList.get(i).getReplyUserID();
					replyID = replyList.get(i).getReplyID();
				
      out.write("\r\n");
      out.write("				<tbody id=\"reply");
      out.print(replyID);
      out.write("\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td style=\"text-align: left;\" colspan=\"2\" >\r\n");
      out.write("							");
      out.print(replyList.get(i).getReplyUserName()
								.replaceAll("<", "&lt")
								.replaceAll(">", "&gt")
								.replaceAll("\n", "<br>"));
      out.write('(');
      out.print(replyUserID);
      out.write(")<br>\r\n");
      out.write("							<span id='update");
      out.print(replyID);
      out.write("'><span id ='content");
      out.print(replyID);
      out.write('\'');
      out.write('>');
      out.print(replyList.get(i).getReplyContent()
									.replaceAll("<", "&lt")
									.replaceAll(">", "&gt")
									.replaceAll("\n", "<br>"));
      out.write("</span></span><br> \r\n");
      out.write("							");
      out.print(replyList.get(i).getReplyDate().substring(0, 11) 
							+ replyList.get(i).getReplyDate().substring(11, 13) + "시"
							+ replyList.get(i).getReplyDate().substring(14, 16) + "분");
      out.write(" \r\n");
      out.write("							<a href=\"javascript:void(0);\" id=\"");
      out.print(replyID);
      out.write("\"\r\n");
      out.write("								onclick=\"reComment(this.id,");
      out.print(replyID);
      out.write(',');
      out.print(bbsID);
      out.write(",'');\">답글</a> \r\n");
      out.write("							");

 							if (userID != null && userID.equals(replyUserID)) {
 							
      out.write(" \r\n");
      out.write(" 							<a href=\"javascript:void(0);\"\r\n");
      out.write("								onclick=\"update(");
      out.print(replyID);
      out.write(',');
      out.write(' ');
      out.print(bbsID);
      out.write(");\">수정</a> \r\n");
      out.write(" 							<a href=\"replyDeleteAction.jsp?bbsID=");
      out.print(bbsID);
      out.write("&replyID=");
      out.print(replyID);
      out.write("\"\r\n");
      out.write("								onclick=\"return confirm('정말로 삭제하시겠습니까?')\">삭제</a> \r\n");
      out.write("							");

							 }
 							
      out.write("\r\n");
      out.write(" 						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</tbody>\r\n");
      out.write("				");

				//댓글ID를 groupID로 같은 댓글을 확인하고 출력
					if (replyDAO.getGroupID(replyID) == -1) {
						PrintWriter script = response.getWriter();
						script.println("<script>");
						script.println("alert('SQL 오류.')");
						script.println("location.href = 'bbs.jsp'");
						script.println("</script>");
					}
					if (replyDAO.getGroupID(replyID) != 0) {
						ArrayList<Reply> reComent = replyDAO.getList(bbsID, replyID);
					
					for (int j = 0; j < reComent.size(); j++) {
						replyUserID = reComent.get(j).getReplyUserID();
						int reComentID = reComent.get(j).getReplyID();
				
      out.write("\r\n");
      out.write("				<tbody id=\"reply");
      out.print(reComentID);
      out.write("\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"1\" width=\"5%\"></td>\r\n");
      out.write("						<td style=\"text-align: left;\">\r\n");
      out.write("							");
      out.print(reComent.get(j).getReplyUserName()
								.replaceAll("<", "&lt")
								.replaceAll(">", "&gt")
								.replaceAll("\n", "<br>"));
      out.write('(');
      out.print(replyUserID);
      out.write(")\r\n");
      out.write("							");
if( !replyDAO.getGroupUserName(reComent.get(j).getGroupUserID()).equals(null) &&
									!replyDAO.getGroupUserName(reComent.get(j).getGroupUserID()).equals("")){
      out.write("\r\n");
      out.write("								▶");
      out.print(replyDAO.getGroupUserName(reComent.get(j).getGroupUserID()));
      out.write('(');
      out.print( reComent.get(j).getGroupUserID());
      out.write(")\r\n");
      out.write("							");
} 
      out.write("<br>\r\n");
      out.write("							<span id='update");
      out.print(reComentID);
      out.write("'><span id ='content");
      out.print(reComentID);
      out.write('\'');
      out.write('>');
      out.print(reComent.get(j).getReplyContent()
								.replaceAll("<", "&lt")
								.replaceAll(">", "&gt")
								.replaceAll("\n", "<br>"));
      out.write("</span></span><br> \r\n");
      out.write("							");
      out.print(reComent.get(j).getReplyDate().substring(0, 11) 
							+ reComent.get(j).getReplyDate().substring(11, 13) + "시"
							+ reComent.get(j).getReplyDate().substring(14, 16) + "분");
      out.write(" \r\n");
      out.write("							<a href=\"javascript:void(0);\" id=\"");
      out.print(reComentID);
      out.write("\"\r\n");
      out.write("								onclick=\"reComment(this.id,");
      out.print(replyID);
      out.write(',');
      out.print(bbsID);
      out.write(',');
      out.write('\'');
      out.print(replyUserID);
      out.write("');\">답글</a> \r\n");
      out.write("							");

 							if (userID != null && userID.equals(replyUserID)) {
 							
      out.write(" \r\n");
      out.write(" 								<a href=\"javascript:void(0);\"\r\n");
      out.write("									onclick=\"update(");
      out.print(reComentID);
      out.write(',');
      out.write(' ');
      out.print(bbsID);
      out.write(");\">수정</a>\r\n");
      out.write("								<a href=\"replyDeleteAction.jsp?bbsID=");
      out.print(bbsID);
      out.write("&replyID=");
      out.print(reComentID);
      out.write("\"\r\n");
      out.write("									onclick=\"return confirm('정말로 삭제하시겠습니까?')\" >삭제</a>\r\n");
      out.write("							");

							}
							
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</tbody>\r\n");
      out.write("				");

						}
					}
				}
				
      out.write("\r\n");
      out.write("				<form method=\"post\" id='reply' action=\"replyAction.jsp\">\r\n");
      out.write("					<input type=\"hidden\" name=\"groupID\" value=\"0\"> \r\n");
      out.write("					<input type=\"hidden\" name=\"groupUserID\" value=\"\"> \r\n");
      out.write("					<input type=\"hidden\" name=\"bbsID\" value=\"");
      out.print(bbsID);
      out.write("\">\r\n");
      out.write("					<table class=\"table table-striped\">\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td colspan=\"1\" width=\"90%\">\r\n");
      out.write("								<textarea id=\"reply\"\r\n");
      out.write("									class=\"form-control\" placeholder=\"댓글 내용\" name=\"replyContent\"\r\n");
      out.write("									maxlength=\"1000\" style=\"height: 70px; resize: none;\"></textarea>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<input type=\"submit\" class=\"btn btn-primary\" value=\"댓글 작성\">\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("				</form>\r\n");
      out.write("				\r\n");
      out.write("			<a href=\"bbs.jsp\" class=\"btn btn-primary\">목록</a>\r\n");
      out.write("			");

			if (userID != null && userID.equals(bbs.getUserID())) {
			
      out.write("\r\n");
      out.write("			<a href=\"update.jsp?bbsID=");
      out.print(bbsID);
      out.write("\" class=\"btn btn-primary\">수정</a>\r\n");
      out.write("			<a onclick=\"return confirm('정말로 삭제하시겠습니까?')\"\r\n");
      out.write("				href=\"deleteAction.jsp?bbsID=");
      out.print(bbsID);
      out.write("\" class=\"btn btn-primary\">삭제</a>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("	<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
